--------------------------------------------------------
--  File created - Friday-November-17-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BRANDS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BRANDS" ("BRANDID" NUMBER, "NAME" VARCHAR2(20), "SCORE" NUMBER DEFAULT 10, "INCREASED" VARCHAR2(5) DEFAULT 'true') SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM"
REM INSERTING into SCOTT.BRANDS
SET DEFINE OFF;
Insert into SCOTT.BRANDS (BRANDID,NAME,SCORE,INCREASED) values (7,'UNACADEMY',10,'true');
Insert into SCOTT.BRANDS (BRANDID,NAME,SCORE,INCREASED) values (8,'BYJUS',10,'true');
--------------------------------------------------------
--  DDL for Index SYS_C007472
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C007472" ON "SCOTT"."BRANDS" ("BRANDID") PCTFREE 10 INITRANS 2 MAXTRANS 255  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Trigger BRANDS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."BRANDS_TRIGGER" 
BEFORE INSERT ON BRANDS
FOR EACH ROW
BEGIN
  :NEW.BRANDID := BRANDIDS.NEXTVAL;
END;

ALTER TRIGGER "SCOTT"."BRANDS_TRIGGER" ENABLE
--------------------------------------------------------
--  Constraints for Table BRANDS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BRANDS" ADD PRIMARY KEY ("BRANDID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "SCOTT"."BRANDS" MODIFY ("NAME" NOT NULL ENABLE)
